### ISSUE TITLE
Channel member

### ISSUE THREAD

**Issue by Chicanoss** [kbarbry/ft_transcendence#25]
Channel member service :

- Modify the create to add the logic of MaxUser
- make maxuser usefull in the create and the delete
- Create must make usefull UserBlocked/User Invited => Channel

Channel member Spec :

- test updatemember ID
- cannot change Channel ID/ User ID/CreatedAT (Make exceptions)
- Delete "makeitClean" in beforeAll
- Edit names of invalid Data test

Database : 

Make three array : 
- Admin + user Member
 - user Invited
 - user Blocked
(User invited and block need 2 more models + services )

**Comment by kbarbry** [comment]
branch merged
