### ISSUE TITLE
Relation Blocked

### ISSUE THREAD

**Issue by Chicanoss** [kbarbry/ft_transcendence#29]
relation Blocked service :

add a check in the create : If the user has sended you a request and you blocked him => delete the request (make a test)
add a 2nd check , if you send a request to the user and then you block him => Delete request (make a test)
if  a friedn block you, delete the friend relation, same in the other side. (make a test)

relation blocked Spec : 

test invalid id : UserA && UserB

**Comment by cben-bar** [comment]
add 2 tests with invalid ID in spec: OK

**Comment by cben-bar** [comment]
all the implementation is complete, all that remains is to create the tests
